# -*- coding: utf-8 -*-
"""practical day 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8VCs-WrE1Wv8YGPDqUberH74vRhGEx5
"""

a=10
print(type(a))
print(id(a))

num=a
print(id(num))
num=20
print(id(num))

a=500
x=500
print(id(a), id(x))
print(a is x)
print(a==x)

for i in range(1,5):
  for j in range(1,i+1):
    print("*",end=" ")
  print()

for i in range(1,4):
  for j in range(1,5):
    print(i,end=" ")
  print()

n=4
for i in range(1,4):
  for j in range(1,5):
    print(n,end=" ")
  n-=1
  print()

n=1
for i in range(1,5):
  for j in range(1,i+1):
   print(n,end=" ")
   n+=1
  print()

n=1
for i in range(1,5):
  for j in range(1,i+1):
    print(n,end=" ")
  print()

p=2
for i in range(p):
  n=10
  for j in range(p+2):
    print(n,end=" ")
    n+=1
  print()

for i in range(1,5):
  for j in range(5,i,-1):
    print("*",end=" ")
  print()

for i in range(1,5):
  for j in range(i,5):
    print("*",end=" ")
  print()

n=4
for i in range(1,5):
  for j in range(i,5):
    print(n,end=" ")
  n-=1
  print()

for i in range(1,5):
  n=1
  for j in range(i,5):
    print(n,end=" ")
    n+=1
  print()

n=1
for i in range(1,5):
  for j in range(i,5):
    print(n,end=" ")
    n+=1
  print()

for i in range(1,5):
  n=7
  for j in range(i,5):
    print(n,end=" ")
    n+=1
  print()

a=65
for i in range(1,5):
  for j in range(i,5):
   print(chr(a),end=" ")
   a+=1
  print()

for i in range(5,2,-1):
  print("#")
  for x in range(4,1,-1):
   print("$",end=" ")
  print()

for i in range(1,10):
   total=0
   total+=i
print(total)

#ord("A")
#ord to print ASCII value
#chr to print character based on ASCII value

a=97
for i in range(1,5):
  for j in range(1,i+1):
    print(chr(a),end=" ")
    a+=1
  print()

a=20
for i in range(1,4):
  for j in range(i,5):
    print(a,end=" ")
    a+=1
  print()

a=90
for i in range(1,4):
  for j in range(i,4):
    print(chr(a),end=" ")
  a-=1
  print()

a=68
for i in range(1,5):
  for j in range(1,i+1):
    print(chr(a),end="  ")
    a+=1
  print()

a=4
for i in range(1,4):
  for j in range(1,i+1):
    print(a,end=" ")
    a+=2
  print()

a=1
for i in range(1,4):
  for j in range(1,5):
    print(a,end=" ")
    a*=2
  print()

for i in range(1,5):
  for j in range(1,i+1):
    print("*",end=" ")
  print()
for i in range(1,4):
  for j in range(i,4):
    print("*",end=" ")
  print()

for i in range(1,5):
  for k in range(i):
    print(" ",end=" ")
  for j in range(i,5):
    print("*",end=" ")
  print()
for i in range(2,5):
  for k in range(i,5):
    print(" ",end=" ")
  for j in range(i):
    print("*",end=" ")
  print()

